concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "windows-runner"
  url = "https://gitlab.userv.ru"
  id = 1
  token = "glrt-wsS5w_l4CIzAzFWtlU8dh286MQp0OjEKdTp5Cw.01.1207y0jvo"
  token_obtained_at = 2025-12-10T04:24:40Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  tls-ca-file = "C:\\GitLab-Runner\\gitlab.crt"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]